services:
  nest-app:
    container_name: i-schools-nest
    image:
    depends_on:
      - postgres
    ports:
      - 8000:3000
    restart: always
    volumes:
      - ~/workplace/i-schools-nest/logs:/app/logs

  postgres:
    container_name: i-schools-postgresdb
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file: '.env'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
