services:
  nest-app-1:
    container_name: i-schools-nest-1
    image:
    restart: always
    env_file: '.env'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ~/workplace/i-schools-nest/logs/app1:/app/logs

  nest-app-2:
    container_name: i-schools-nest-2
    image:
    restart: always
    env_file: '.env'
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ~/workplace/i-schools-nest/logs/app2:/app/logs

  nginx:
    build: ../nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /www/server/nginx/logs:/var/log/nginx
      - /ssl/:/etc/nginx/certs/
    depends_on:
      - nest-app-1
      - nest-app-2
