name: Master-And-Deploy

#on:
#  push:
#    # 每次 push tag 时进行构建，不需要每次 push 都构建。使用通配符匹配每次 tag 的提交，记得 tag 名一定要以 v 开头
#    tags:
#      - v*

on:
  push:
    branches:
      - 'master'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo secrets
        run: |
          echo -e "$ENV_FILE" > .env
        shell: bash
        env:
          ENV_FILE: ${{secrets.SERVER_ENV_PROD}}

      - name: Set image registry
        env:
          REGISTRY: ${{secrets.ALIYUN_REGISTRY_URL }}
          NAMESPACE: ${{vars.ACR_NAMESPACE}}
        run: |
          sed -i 's/image:/image: $REGISTRY\/$NAMESPACE\/i-schools-service:master/' docker-compose.yml

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: i-schools-service

      - name: Log in to aliyun private docker Registry
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          password: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags }}
          REGISTRY: ${{secrets.ALIYUN_REGISTRY_URL }}
          NAMESPACE: ${{vars.ACR_NAMESPACE}}
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$IMAGE_TAG .
          docker push $REGISTRY/$NAMESPACE/$IMAGE_TAG

      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_KEY }}
          source: './docker-compose.yml,./.env'
          target: '~/workplace/'
          overwrite: true
          strip_components: 1

      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_KEY }}
          script: |
            docker login --username=${{ secrets.ALIYUN_ACCESS_KEY_ID }} --password=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} ${{ secrets.ALIYUN_REGISTRY_URL }}
            cd ~/workplace
            docker-compose stop || true
            docker-compose down || true
            docker compose pull
            docker compose up -d --force-recreate
            docker system prune -a -f
