name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo secrets
        run: |
          echo -e "${{secrets.SERVER_ENV_PROD}}" > .env
        shell: bash

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: i-schools-service

      - name: Log in to aliyun private docker Registry
        uses: aliyun/acr-login@v1
        with:
          login-server: ${{ secrets.ALIYUN_REGISTRY_URL }}
          username: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          password: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.tags[0] }}
          REGISTRY: ${{ secrets.ALIYUN_REGISTRY_URL }}
          NAMESPACE: ${{ vars.ACR_NAMESPACE }}
        run: |
          docker build -t $REGISTRY/$NAMESPACE/$IMAGE_TAG .
          docker push $REGISTRY/$NAMESPACE/$IMAGE_TAG

      - name: Set image registry
        run: |
          sed -i "4s/image:/image: ${{secrets.ALIYUN_REGISTRY_URL }}\/${{vars.ACR_NAMESPACE}}\/${{ steps.meta.outputs.tags[0] }}/" docker-compose.yml

      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_KEY }}
          source: './docker-compose.yml,./.env'
          target: '~/workplace/i-schools-nest/'
          overwrite: true
          strip_components: 1

      - name: Deploy to Aliyun
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_KEY }}
          script: |
            docker login --username=${{ secrets.ALIYUN_ACCESS_KEY_ID }} --password=${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} ${{ secrets.ALIYUN_REGISTRY_URL }}
            cd ~/workplace
            docker-compose stop || true
            docker-compose down || true
            docker compose pull
            docker compose up -d --force-recreate
            docker system prune -a -f
